### ISSUE TITLE
P1 Assignment Checklist

### ISSUE THREAD

**Issue by lujorryn** [JuneOh710/PetPal#14]
A checklist of all our P1 assignment grading specs.
- [x] Landing Page (this could be the main search page or sign-up/log-in page) [2 marks]
   - [x] User should not be logged in on this page
- [x] Login Page [4 marks]
   - [x] Initial view
   - [x] Same page with error message, e.g., invalid username and password combination.
- [x] Signup Page (one for pet seeker and another for pet shelter) [8 marks]
   - [x] Initial View
   - [x] Same page with error messages, e.g., invalid email address. 
   - [x] You can design this page so that one page handles signup for both pet seeker and pet shelter.
- [x] Search Page [12 marks]
   - [x] Initial view
   - [x] With a filter turned on
   - [x] With a sort option turned on
- [x] Pet Detail Page [8 marks]
   - [x] Should have link to pet adoption page if available
   - [x] Should have some error message for pets in other states, i.e., pending, adopted, withdrawn. 
   -> Pet 2 leads to pet-details-pending.
- [x] Pet Adoption Page [8 marks]
   - [x] Should display the application form (unfilled).
   - [x] Should not be possible if user already has an application for the same pet. Can show an error page. Better yet, the pet detail page disable the link to this page.
- [x] Application Page [8 marks]
   - [x] Shows the current pet adoption application information (filled, and cannot be changed)
   - [x] Can show the conversation between pet shelter and user, or it can go to a separate page.
- [x] Pet Creation Page [8 marks]
- [x] Pet Update Page [2 marks]
   - [x] This should probably look fairly similar to the pet creation page.
- [x] Shelter Detail Page [8 marks]
  - [x] Shelter reviews can go here or in a separate page.
- [x] Shelter Management Page [8 marks] (My Pets in the header, `pet-management.html`
   - [x] Easy to use interface to manage their pet listings
- [x] Account Update Page [10 marks]
   - [x] One for regular users and another for pet shelter
- [x] Notifications [4 marks]
   - [x] Have at least one page (of your choice) show what happens when there is notification, and what happens when you click on the notification icon. It should either take you to a notification page or show a drop down of notifications

**Comment by lujorryn** [comment]
Checklist complete, will close this issue once migration to MarkUs is complete.
